version: '3.3'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - "./frontend/app:/app"
    expose:
      - 3000
    networks:
      - internal

  reverse_proxy:
    build: reverse_proxy
    ports:
      - "3000:3000"
    networks:
      - internal
    depends_on:
      - frontend
      - backend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev

    volumes:
      - "./backend/app:/app"

    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      FT_CLIENT_ID: ${FT_CLIENT_ID}
      FT_CLIENT_SECRET: ${FT_CLIENT_SECRET}
      FT_REDIRECT_URL: ${FT_REDIRECT_URL}
      BASE_URL: ${BASE_URL}

    expose:
      - 3000

    depends_on:
      - database

    networks:
      - internal

  database:
    build:
      context: db
      dockerfile: Dockerfile

    expose:
      - 5432

    volumes:
      - "database:/var/lib/postgresql/data"

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PASSWORD: ${DB_PASSWORD}

    networks:
      - internal

volumes:
  database:


networks:
  internal:
