version: '3.3'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    expose:
      - 3000
    networks:
      - internal
    restart: always

  reverse_proxy:
    build: reverse_proxy
    ports:
      - "3000:3000"
    depends_on:
      - frontend
      - backend
    networks:
      - internal
    restart: always

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    expose:
      - 3000
    networks:
      - internal
    restart: always
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      FT_CLIENT_ID: ${FT_CLIENT_ID}
      FT_CLIENT_SECRET: ${FT_CLIENT_SECRET}

  database:
    build:
      context: db
      dockerfile: Dockerfile
    expose:
      - 5432
    volumes:
      - "database:/var/lib/postgresql/data"
    networks:
      - internal
    restart: always

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PASSWORD: ${DB_PASSWORD}

volumes:
  database:


networks:
  internal:
